### ISSUE TITLE
проверка ДЗ

### ISSUE THREAD

**Issue by JuliaArtes** [JuliaArtes/1_1_fuelConsumption#1]
@coursar проверить ДЗ

**Comment by coursar** [comment]
Пофиксить #2, #3 после чего переоткрыть Issue

**Comment by JuliaArtes** [comment]
@coursar ошибки исправлены

**Comment by JuliaArtes** [comment]
@coursar  исправлено #4 и #5

**Comment by JuliaArtes** [comment]
#6 закрыла через commit
